services:
    app:
        build:
            args:
                user: ${DOCKER_COMPOSE_NAME}_user
                uid: 1000
            context: .
        image: ${DOCKER_COMPOSE_NAME}
        container_name: app_${DOCKER_COMPOSE_NAME}
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www

    db:
        image: mysql:8.0
        container_name: db_${DOCKER_COMPOSE_NAME}
        restart: unless-stopped
        ports:
            - ${DOCKER_COMPOSE_DB_PORT}:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./_docker/mysql:/var/lib/mysql

    nginx:
        image: nginx:1.24-alpine
        container_name: nginx_${DOCKER_COMPOSE_NAME}
        restart: unless-stopped
        ports:
            - ${DOCKER_COMPOSE_NGINX_PORT}:80
        volumes:
            - ./:/var/www
            - ./_docker/nginx:/etc/nginx/conf.d

    mail:
        image: axllent/mailpit:v1.6
        container_name: mail_${DOCKER_COMPOSE_NAME}
        restart: unless-stopped
        ports:
            - 1025:1025
            - 8025:8025
