services:
    app:
        build:
            args:
                user: ${DOCKER_COMPOSE_NAME}_user
                uid: 1000
            context: .
        image: ${DOCKER_COMPOSE_NAME}
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./_docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini

    db:
        image: mysql:8.0
        restart: unless-stopped
        ports:
            - ${DOCKER_COMPOSE_DB_PORT}:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./_docker/mysql:/var/lib/mysql

    nginx:
        image: nginx:1.24-alpine
        restart: unless-stopped
        ports:
            - ${DOCKER_COMPOSE_NGINX_PORT}:80
        volumes:
            - ./:/var/www
            - ./_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    redis:
        image: 'redis:alpine'
        ports:
            - '${REDIS_PORT:-6379}:6379'
        volumes:
            - './_docker/redis/data:/data'
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s

    mail:
        image: axllent/mailpit:v1.6
        restart: unless-stopped
        ports:
            - 1025:1025
            - 8025:8025

    soketi:
        image: 'quay.io/soketi/soketi:latest-16-alpine'
        environment:
            SOKETI_DEBUG: '1'
            SOKETI_METRICS_SERVER_PORT: '9601'
            SOKETI_DEFAULT_APP_ID: 'app-id'
            SOKETI_DEFAULT_APP_KEY: 'app-key'
            SOKETI_DEFAULT_APP_SECRET: 'app-secret'
        ports:
            - '${SOKETI_PORT:-6001}:6001'
            - '${SOKETI_METRICS_PORT:-9601}:9601'